### ISSUE TITLE
How to set the PATH?

### ISSUE THREAD

**Issue by sceliay** [MIPT-Oulu/OAProgression#1]
I have some confusion about the dataset and the path to be set.
I've downloaded 'X-RAY ASSESSMENTS - SAS', unzip, then I get 3 folders: 'Alignment_SAS', 'Quant JSW_SAS',  'Semi-Quant Scoring_SAS'. I put these folders with 'enrollees.sas7bdat' and 'allclinical00.sas7bdat' together, is that right?
Then how to set the path? What's the meaning of 'OAI_META_SRC', 'MOST_META_SRC', 
'OAI_MOST_IMG_SRC' and 'WRKDIR'? 
Moreover, PYTHON 2 or PYTHON 3 should I use?

**Comment by lext** [comment]
Hi,

Thanks a lot for your interest to my work! Some tips.

 - You need to use the provided Dockerfile to have all the dependencies installed. In general you can follow what is done in the Dockerfile to reproduce the environment.
- You won't be able to train the models right away. You will need to pre-localize the knee joints first (read the paper carefully). There exist multiple options for that. We do not provide knee joint detector in this repository. 

Some naming-related clarification:
- `OAI_MOST_IMG_SRC` - a directory with pre-localized knee joints
- `WRKDIR` - workdir (where all the results and the snapshots are stored)
- `OAI_META_SRC` - a directory with the OAI metadata
- `MOST_META_SRC` - a directory with MOST metadata

I hope it helps :-)
